name =input("Enter your name:")
age =int(input("Enter your age:"))
city=input("Enter the city in which you live:")
print(f"Hello {name}!")
print(f"You are {age} years old.")
print(f"You live in {city}.")
